### ISSUE TITLE
コードルールとフォーマッターの設定

### ISSUE THREAD

**Issue by kokiito** [CollectiveReview/react-yjs#31]
**Is your feature request related to a problem? Please describe.**
コードを編集する環境によっていろいろなコード書き方ができてしまう。
フォーマットをそれぞれだったりしてコードが汚くなって可読性が下がってしまう。

**Describe the solution you'd like**
ESLintによってコードのルールを決定し、フォーマットをprettierによって揃える

**Additional context**

- https://zenn.dev/resistance_gowy/articles/91b4f62b9f48ec#(1)next.js%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB
- https://nextjs.org/docs/pages/building-your-application/configuring/eslint#recommended-plugin-ruleset

**Comment by kokiito** [comment]
最初に設定しておくと個人でコード書く時も便利

**Comment by kokiito** [comment]
これが1番、わかりすくてよかった
https://blog.monorevo.jp/post-2104

**Comment by kokiito** [comment]
pushする権限をくれたら設定します

**Comment by psmuler** [comment]
push権限付与しました
